const errorTypes = {
    INVALID_BLOCK_DATA: 'INVALID_BLOCK_DATA',
    BLOCK_CANNOT_BE_ADDED: 'BLOCK_CANNOT_BE_ADDED',
    INVALID_HEIGHT: 'INVALID_HEIGHT',
    BLOCK_NOT_FOUND_IN_BLOCKCHAIN: 'BLOCK_NOT_FOUND',
    BLOCK_NOT_FOUND_IN_MEMPOOL: 'BLOCK_NOT_FOUND_IN_MEMPOOL',
    BLOCKCHAIN_UNAVAILABLE: 'BLOCKCHAIN_UNAVAILABLE',
    ERROR_WHILE_DECODING_BLOCK: 'ERROR_WHILE_DECODING_BLOCK',
    TIMEOUT: 'TIMEOUT',
    INVALID_WALLET_ADDRESS_IN_REQUEST: 'INVALID_WALLET_ADDRESS_IN_REQUEST',
    INVALID_SIGNATURE_IN_REQUEST: 'INVALID_SIGNATURE_IN_REQUEST',
    NO_PENDING_WALLIDATION_FOR_WALLET: 'NO_PENDING_WALLIDATION_FOR_WALLET',
    VALIDATION_WINDOW_EXPIRES: 'VALIDATION_WINDOW_EXPIRES',
    MESSAGE_VALIDATION_FAILED: 'MESSAGE_VALIDATION_FAILED',
    INVALID_HASH_IN_REQUEST: 'INVALID_HASH_IN_REQUEST'
};

module.exports = {
    errorTypes
};