const errorTypes = {
    INVALID_BLOCK_DATA: 'INVALID_BLOCK_DATA',
    BLOCK_CANNOT_BE_ADDED: 'BLOCK_CANNOT_BE_ADDED',
    INVALID_HEIGHT: 'INVALID_HEIGHT',
    BLOCK_NOT_FOUND_IN_BLOCKCHAIN: 'BLOCK_NOT_FOUND',
    BLOCK_NOT_FOUND_IN_MEMPOOL: 'BLOCK_NOT_FOUND_IN_MEMPOOL',
    BLOCKCHAIN_UNAVAILABLE: 'BLOCKCHAIN_UNAVAILABLE',
    TIMEOUT: 'TIMEOUT'
};

module.exports = {
    errorTypes
};